kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9200
      name: rest
      targetPort: 9200
    - protocol: TCP
      port: 9300
      name: inter-node
      targetPort: 9300
